Change request task
xlab-steampunk/servicenow.itsm pull request #1
Opened 2021-07-02 09:14 UTC by MysteriousWolf

##### SUMMARY
Adds a specification for the change_request_task module with usage examples.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
- change_request_task and change_request_task_info

##### ADDITIONAL INFORMATION
The specification allows users to modify all [standard parameters](https://docs.servicenow.com/bundle/quebec-it-service-management/page/product/change-management/task/create-a-change-task.html) defined in the ServiceNow docs, as well as properties required to create and close tasks.

2021-07-05 04:54 UTC, tadeboro approved these changes

2021-07-12 08:46 UTC, tadeboro requested changes
I did my initial review and I found a few areas that could use some improvement, especially around usability (providing misleading error messages is a no-go).

2021-07-12 08:46 UTC, tadeboro commented on plugins/module_utils/validation.py
> +def check_value_compatibility(compatible_states, property_name, params, record=None):
As far as I can tell, this function is not used at all in the code. Is there a reason why we have it defined?

2021-07-12 08:46 UTC, tadeboro commented on plugins/module_utils/validation.py
> +):
Why does this function name hint at the state validation? As far as I can tell, all this function does is make sure certain parameter contains a valid value. And it does this in a quite convoluted way.

I would suggest renaming the function into something more sensible and simplifying it along those lines:

```
# Get value in effect
value = params[property_name]
if value is None:
    value = (record or {}).get(property_name)

# Make sure value is not in the set of invalid values
return value not in incompatible_states, value
```

2021-07-12 08:46 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +      - The configuration item (CI) or service name that the change task applies to.
We should inform the user here then CI names are not guaranteed to be unique. If that is the case, the module will fail and do nothing.

2021-07-12 08:46 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +    "assignment_group",
Is this really copy-paste parameter or should we do a lookup of the assignment group's ID?

2021-07-12 08:46 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +
Just drop this part in all other examples since 1) authentication is not that interesting once you saw it once and 2) this is not how instance data is usually passed to the modules.

2021-07-12 08:46 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +    if params.get("state") == "closed":
```suggestion
    if params["state"] == "closed":
```

2021-07-12 08:46 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +    if params.get("on_hold"):
```suggestion
    if params["on_hold"]:
```

2021-07-12 08:46 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +                'Cannot put a task in state "{}" on hold'.format(compatibility[1])
This error message is bad because it will mislead users in certain scenarios. For example, if the user works on an existing task that is already on hold and tries to change its state to `canceled`, the error message makes no sense since our poor user is not trying to put anything on hold at all.

2021-07-12 08:55 UTC, MysteriousWolf commented on plugins/module_utils/validation.py
> +def check_value_compatibility(compatible_states, property_name, params, record=None):
I put it there mostly for future use since it is very similar to the other incompatibility check, but I agree that it could be omitted since it possibly won't be used anywhere anyway.

2021-07-12 09:52 UTC, MysteriousWolf commented on plugins/modules/change_request_task.py
> +                'Cannot put a task in state "{}" on hold'.format(compatibility[1])
Not only that, but it doesn't even check whether the task may already be on hold and the user wants to set the state to something incompatible. Working on a fix that should cover both cases and provide better feedback.

2021-07-19 06:17 UTC, tadeboro requested changes

2021-07-19 06:17 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +version_added: 1.0.0
```suggestion
version_added: 1.2.0
```

2021-07-19 06:17 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +      - Note that contrary to configuration_item_id, configuration item names may not uniquely identify a record.
```suggestion
      - Note that contrary to I(configuration_item_id), configuration item names may not uniquely identify a record.
```

2021-07-19 06:17 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +      - Note that contrary to change_request_id, change request number may not uniquely identify a record.
```suggestion
      - Note that contrary to I(change_request_id), change request number may not uniquely identify a record.
```

2021-07-19 06:17 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +            )
Why is this different from the previous branch? I would assume the same validation criteria applies here.

2021-07-19 06:17 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +    return True
This feels a bit awkward. Since we are only interested in adjusting the result in case any of the two date fields are different in representation but actually represent the same point in time, we should probably do something like this:

```suggestion
def is_superset_with_date(superset, candidate):
    datetime_fields = ("planned_start_date", "planned_end_date")
    
    for k in datetime_fields:
        if k in candidate and superset.get(k, "").replace("T", " ") != candidate[k].replace("T", " "):
            return False
    
    return utils.is_superset(superset, dict((k, v) for k, v in candidate.items() if k not in datetime_fields))
```

2021-07-19 06:41 UTC, MysteriousWolf commented on plugins/modules/change_request_task.py
> +            )
When testing the plugin, I found out that ServiceNow allows changing task states to closed or cancelled even if it's currently on hold. Contrary to that, it does not allow you to set it on hold when in those two states or when it's still "pending", which is also reflected in the snow UI, so I separated them into two different branches.

2021-07-20 06:17 UTC, tadeboro requested changes
Overall, this PR is turning out to be a great contribution to the codebase. I did find some issues, but we are progressing really nicely here. Thank you, @MysteriousWolf, for your effort!

2021-07-20 06:17 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +            )
> When testing the plugin, I found out that ServiceNow allows changing task states to closed or cancelled even if it's currently on hold. Contrary to that, it does not allow you to set it on hold when in those two states or when it's still "pending", which is also reflected in the snow UI, so I separated them into two different branches.

But if I understand this correctly, this is not what this check enforces. Let us assume that we have an existing task that has `state=in_progress` and `on_hold=true`. If I run the following task, the validation will abort the task execution:

```
- servicenow.itsm.change_request_task:
    number: 1234
    state: closed
    on_hold: true
```

But if I understand you correctly, this task should succeed because transitioning from `in_progress` to `closed`is valid even when the task is on hold.

2021-07-20 06:17 UTC, tadeboro commented on plugins/module_utils/validation.py
> +    value = params[property_name] or (record or {}).get(property_name)
Is this really what we want here? `None` is not the only falsy thing in Python, so this has the potential to give us trouble. For example, if the user explicitly sets one of the parameters to `""`, this line will "ignore" the empty string and instead return whatever is in the record.

And while on its own this behavior would note problematic, combined with https://github.com/xlab-steampunk/servicenow.itsm/blob/48b521fd7e83a22994def9b010b674150c99e8a8/plugins/module_utils/utils.py#L11-L19 does make things bad because the validation and payload building now behave differently.

2021-07-20 06:17 UTC, tadeboro commented on tests/unit/plugins/module_utils/test_validation.py
> +        print(result)
```suggestion
```

2021-07-20 06:17 UTC, tadeboro commented on tests/unit/plugins/module_utils/test_validation.py
> +        ],
We should also add some test samples for edge cases, for example, where the `params["p"] = ""`. Also, testing things on other types of values apart from strings should be done (we do not need new tests for this, we can use ints in some other tests, again making sure things like `0` that are falsy produce the correct result).

2021-07-20 06:17 UTC, tadeboro commented on tests/unit/plugins/module_utils/test_validation.py
> +        ],
The same comments apply here as for the previous test.

2021-07-20 06:17 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +      - A change task can be put on hold when I(state) is not in the C(pending), C(canceled), or C(closed)
Is this correct? If I remember correctly, we talked about this and concluded that we could not put a task on hold when it is pending, canceled, or closed.

2021-07-20 06:17 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +      - If the task I(type) is C(implementation), the I(planned_start_date) and I(planned_end_date) values
The comment about the `planned_start_date` parameter should live in the previous description.

2021-07-20 06:17 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +def validate_params(params, change_request=None):
```suggestion
def validate_params(params, change_task=None):
```

2021-07-20 06:17 UTC, tadeboro commented on tests/unit/plugins/modules/test_change_request_task.py
> +        print(result)
```suggestion
```

2021-07-20 06:17 UTC, tadeboro commented on tests/unit/plugins/modules/test_change_request_task.py
> +        print(result)
```suggestion
```

2021-07-20 06:17 UTC, tadeboro commented on tests/unit/plugins/modules/test_change_request_task.py
> +        print(result)
```suggestion
```

2021-07-20 06:17 UTC, tadeboro commented on tests/unit/plugins/modules/test_change_request_task.py
> +                change_request_task.validate_params(params)
Just split those two categories of problems into two test functions. Having conditional logic in unit tests is not the best design. In an ideal world, each unit test is composed of three sections with as few logical constructs as possible: environment setup (if needed), function call, and assertions (if needed).

2021-07-20 06:17 UTC, tadeboro commented on tests/unit/plugins/modules/test_change_request_task.py
> +                change_request_task.validate_params(params, self.VALID_PARAMS_HOLD)
See the previous comment.

2021-07-20 06:17 UTC, tadeboro commented on tests/unit/plugins/modules/test_change_request_task.py
> +    def test_valid_dates(self, record, params):
```suggestion
    def test_same_point_in_time(self, record, params):
```

2021-07-20 06:17 UTC, tadeboro commented on tests/unit/plugins/modules/test_change_request_task.py
> +                dict(planned_start_date="2021-07-09 08:40:34"),
This test case makes sure we detect if we are operating on different dates and should be in a dedicated test together with a companion end date test case.

2021-07-20 06:17 UTC, tadeboro commented on tests/unit/plugins/modules/test_change_request_task.py
> +            (dict(param="2021-07-09 08:40:33"), dict(param="2021-07-09T08:40:33")),
We should move this test case to the `not_a_superset` test and its positive equivalent to the `valid_superset` test.

2021-07-20 06:17 UTC, tadeboro commented on tests/unit/plugins/modules/test_change_request_task.py
> +                dict(planned_start_date=""),
We also need test cases with `None`s and absent parameters in the params dictionary.

2021-07-20 06:17 UTC, tadeboro commented on plugins/modules/change_request_task_info.py
> +            else utils.filter_dict(module.params, "sys_id", "number"),
This multiline if expression should be a separate statement because it makes it hard to see the actual parameters.  And as a side benefit, we will also gain a small speed boost because we will only construct query once and not once per iteration.

2021-07-20 06:26 UTC, MysteriousWolf commented on plugins/module_utils/validation.py
> +    value = params[property_name] or (record or {}).get(property_name)
I agree. While it would work most of the time, it could cause issues when working with not None, falsy values.

2021-07-20 06:36 UTC, MysteriousWolf commented on plugins/modules/change_request_task.py
> +      - A change task can be put on hold when I(state) is not in the C(pending), C(canceled), or C(closed)
It's worded a bit awkwardly. I'll put the negation sooner in the sentence to clear up the possible confusion.

2021-07-20 09:43 UTC, MysteriousWolf commented on tests/unit/plugins/modules/test_change_request_task.py
> +            (dict(param="2021-07-09 08:40:33"), dict(param="2021-07-09T08:40:33")),
I don't think the valid superset equivalent is necessary since we already test for valid dates in `test_same_point_in_time`, but I did move this specific case to `not_a_superset` test since it doesn't have anything to do with dates in the background.

2021-07-21 13:40 UTC, tadeboro requested changes
Almost there ;)

2021-07-21 13:40 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +    change = table_client.get_record("change_task", query)
```suggestion
    task = table_client.get_record("change_task", query)
```

Or `change_task`, whatever feels more natural. But `change` is not OK because it is misleading.

2021-07-21 13:40 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +            )
The logic behind this is not entirely clear to me. Let us assume that we have an existing task that has `state=in_progress` and `on_hold=true`. If I run the following task, the validation will abort the task execution:

```
- servicenow.itsm.change_request_task:
    number: 1234
    state: closed
    on_hold: true
```

But if I understand you correctly, this task should succeed because transitioning from `in_progress` to `closed` is valid even when the task is on hold.

2021-07-22 05:16 UTC, MysteriousWolf commented on plugins/modules/change_request_task.py
> +            )
On one hand this is true, the task could be put on hold, but on the other, it doesn't make sense to change the state to closed and put the task on hold in the same Ansible task (snow UI doesn't allow you to do that either), but you can still close a task that is already on hold. If you closed it already, why put it on hold?

2021-07-22 05:43 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +            )
The problem here is the misleading error message. When my example task fails, it will say that we cannot put the task on hold because of the incompatible state. This is not true since the task is already on hold and users will be angry at us because we are trying to do something that does not need to be done.

Ansible playbook is all about the final state and this makes a difference interpreting the actions required. My example does not say "move task to closed state and put it on hold." It says "make sure task is closed and on hold." And we should only complain if the final state is invalid or if the transition from the current to the end state is impossible. And neither is true in this example.

2021-07-22 06:08 UTC, MysteriousWolf commented on plugins/modules/change_request_task.py
> +            )
Do you think adding an exception for when the task isn't really put `on_hold`, but rather just making sure that it's already on hold is an option? In this case we could make sure it's on hold, but wouldn't really be consistent and could fail if the state needs changing.

2021-07-22 06:51 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +            )
As far as I can tell, we need to handle the following cases:

 1. If the existing task is on hold and we are setting on hold state to false or not setting it at all, everything goes.
 2. If the existing task is on hold and we are also setting on hold to true, the final state cannot be pending (and the error should reflect that the state move is problematic, not the on hold status).
 3. If the existing task is not on hold and we are setting on hold state to false or not setting it at all, everything goes.
 4. If the existing task is not on hold and we are setting the on hold to true, the final state cannot be pending, canceled, closed.

Did I miss anything here?

2021-07-22 07:30 UTC, MysteriousWolf commented on plugins/modules/change_request_task.py
> +            )
At first I built this in a way to follow the UI constraints, but I did a bit more testing and the API doesn't seem to really care what combination of these parameters you give. I guess leaving out all the validation of these two parameters could also be an option.

2021-07-22 07:43 UTC, tadeboro commented on plugins/modules/change_request_task.py
> +            )
If this is the case, then yes, drop the validation. Simpler is better in most cases.

2021-07-22 10:45 UTC, tadeboro requested changes
Once we rebase this, we are ready to go.

2021-07-23 15:10 UTC, tadeboro approved these changes

2021-07-23 15:10 UTC, merged